import { Project, Slide } from '../types';

export interface StarterTemplate {
  id: string;
  name: string;
  category: Project['category'];
  description: string;
  badge: string;
  slideCount: number;
  projectData: Omit<Project, 'id' | 'createdAt' | 'updatedAt'>;
}

export const STARTER_TEMPLATES: StarterTemplate[] = [
  {
    id: 'tpl-pengumuman-umum',
    name: 'Pengumuman Penting / Edaran',
    category: 'pengumuman',
    description: 'Template untuk mengumumkan rapat warga, himbauan, atau kabar penting Karang Taruna.',
    badge: 'Pengumuman',
    slideCount: 3,
    projectData: {
      title: 'Pengumuman Rapat Anggota Bulanan',
      category: 'pengumuman',
      aspectRatio: '1:1',
      themeId: 'kt-default',
      logoType: 'default',
      orgName: 'Karang Taruna Sukamaju',
      author: 'Pengurus Karang Taruna',
      captionText: `🚨 PENGUMUMAN PENTING KARANG TARUNA 🚨\n\nDiberitahukan kepada seluruh pemuda & warga, akan dilaksanakan Rapat Anggota Bulanan Karang Taruna.\n\nMohon kehadiran seluruh pengurus dan perwakilan pemuda RT/RW.\n\nMari bersama majukan desa kita! 💪🇮🇩`,
      hashtags: ['KarangTaruna', 'PemudaBerkarya', 'RapatBulanan', 'Sukamaju', 'GotongRoyong'],
      slides: [
        {
          id: 's1',
          type: 'intro',
          title: 'PENGUMUMAN PENTING',
          subtitle: 'Rapat Anggota & Koordinasi Pemuda',
          badge: 'INFO RESMI',
          bgType: 'gradient',
          bgGradient: 'linear-gradient(135deg, #D62828 0%, #1D1D1D 100%)',
          body: 'Seluruh Pengurus & Anggota Wajib Hadir',
        },
        {
          id: 's2',
          type: 'content',
          title: 'Agenda & Waktu Pelaksanaan',
          subtitle: 'Catat Tanggal dan Tempatnya',
          badge: 'AGENDA',
          bgType: 'solid',
          bgColor: '#FFFFFF',
          listItems: [
            '📅 Hari/Tanggal: Sabtu, 28 Juli 2026',
            '⏰ Waktu: 19.30 WIB - Selesai',
            '📍 Lokasi: Balai Pertemuan RW 05',
            '📝 Agenda: Persiapan HUT RI & Pembentukan Panitia Lomba',
          ],
        },
        {
          id: 's3',
          type: 'cta',
          title: 'Konfirmasi Kehadiran',
          subtitle: 'Hubungi Sekretariat / Koordinator RT',
          badge: 'CONTACT PERSON',
          bgType: 'solid',
          bgColor: '#F8FAFC',
          ctaPhone: '+62 812-3456-7890 (Budi - Sekretaris)',
          ctaIg: '@karangtaruna.sukamaju',
          ctaLocation: 'Balai Warga Sukamaju',
          ctaQrText: 'Scan untuk kirim konfirmasi WhatsApp',
        },
      ],
    },
  },
  {
    id: 'tpl-gotong-royong',
    name: 'Kerja Bakti & Gotong Royong',
    category: 'kegiatan',
    description: 'Post Carousel ajakan kerja bakti kebersihan lingkungan dan pemuda.',
    badge: 'Kegiatan',
    slideCount: 4,
    projectData: {
      title: 'Kerja Bakti Akbar Bersih Desa',
      category: 'kegiatan',
      aspectRatio: '4:5',
      themeId: 'kt-emerald',
      logoType: 'default',
      orgName: 'Karang Taruna Tunas Bangsa',
      author: 'Bidang Lingkungan Hidup',
      captionText: `🌱 BERSAMA JAGA KEBERSIHAN LINGKUNGAN 🌱\n\nYuk ikutan Kerja Bakti Akbar Pemuda Karang Taruna! Kita bersihkan selokan, rapikan taman desa, dan cat gapura warga.\n\nJangan lupa bawa alat kerja bakti masing-masing ya! Makanan & kopi disediakan gratis ☕🍩`,
      hashtags: ['KerjaBakti', 'GotongRoyong', 'BersihDesa', 'KarangTarunaPeduli', 'PemudaHijau'],
      slides: [
        {
          id: 's1',
          type: 'intro',
          title: 'KERJA BAKTI AKBAR',
          subtitle: 'Aksi Pemuda Peduli Lingkungan Desa',
          badge: 'GERAKAN PEMUDA',
          bgType: 'gradient',
          bgGradient: 'linear-gradient(135deg, #2A9D8F 0%, #264653 100%)',
          body: 'Bersatu Menjaga Kebersihan & Keasrian Lingkungan',
        },
        {
          id: 's2',
          type: 'content',
          title: 'Titik Fokus Kerja Bakti',
          subtitle: 'Pembersihan & Perapihan Wilayah',
          badge: 'SASARAN',
          bgType: 'solid',
          bgColor: '#FFFFFF',
          listItems: [
            '🧹 Pembersihan Saluran Air & Selokan Utama',
            '🌿 Perapihan Taman & Area Publik',
            '🎨 Pengecatan Gapura & Fasilitas Umum',
            '♻️ Pemilahan Sampah Organik & Anorganik',
          ],
        },
        {
          id: 's3',
          type: 'content',
          title: 'Perlengkapan Yang Dibawa',
          subtitle: 'Persiapan Peserta',
          badge: 'PERLENGKAPAN',
          bgType: 'solid',
          bgColor: '#F4F9F8',
          listItems: [
            'Sapu lidi & cangkul kecil',
            'Sarung tangan & masker',
            'Semangat gotong royong!',
            '*(Konsumsi & snack disediakan panitia)',
          ],
        },
        {
          id: 's4',
          type: 'cta',
          title: 'Sampai Jumpa Di Lokasi!',
          subtitle: 'Minggu Pagi, Jam 06.30 WIB di Lapangan Utama',
          badge: 'GABUNG SEKARANG',
          bgType: 'solid',
          bgColor: '#2A9D8F',
          ctaPhone: '+62 857-1122-3344 (Rian)',
          ctaIg: '@kt.tunasbangsa',
          ctaLocation: 'Lapangan Desa Sukamaju',
        },
      ],
    },
  },
  {
    id: 'tpl-hut-ri',
    name: 'Peringatan HUT RI 17 Agustus',
    category: 'hari_besar',
    description: 'Carousel pengumuman lomba 17-an kemerdekaan RI super meriah.',
    badge: 'HUT RI',
    slideCount: 5,
    projectData: {
      title: 'Semarak Lomba 17 Agustus Kemerdekaan',
      category: 'hari_besar',
      aspectRatio: '4:5',
      themeId: 'kt-default',
      logoType: 'default',
      orgName: 'Karang Taruna Unit 08',
      author: 'Panitia HUT RI',
      captionText: `🇮🇩 GEBYAR KEMERDEKAAN RI KE-81 🇮🇩\n\nSambut Hari Kemerdekaan dengan penuh semangat! Karang Taruna mempersembahkan Rangkaian Lomba 17 Agustus untuk anak-anak, remaja, dan dewasa.\n\nTotal Hadiah Jutaan Rupiah + Tropy Juara Umum! 🏆🎁\n\nDaftar sekarang sebelum kuota penuh!`,
      hashtags: ['17Agustus', 'HUTRI81', 'IndonesiaMaju', 'LombaAgustusan', 'KarangTaruna', 'Merdeka'],
      slides: [
        {
          id: 's1',
          type: 'intro',
          title: 'SEMARAK LOMBA 17 AGUSTUS',
          subtitle: 'Nusantara Baru, Indonesia Maju',
          badge: 'GEBYAR KEMERDEKAAN',
          bgType: 'gradient',
          bgGradient: 'linear-gradient(135deg, #D62828 0%, #8B0000 100%)',
          body: 'Total Hadiah Jutaan Rupiah & Doorprize Menarik',
        },
        {
          id: 's2',
          type: 'content',
          title: 'Kategori Lomba Anak-Anak',
          subtitle: 'Minggu, 17 Agustus | 08.00 WIB',
          badge: 'KATEGORI ANAK',
          bgType: 'solid',
          bgColor: '#FFFFFF',
          listItems: [
            '🎈 Makan Kerupuk & Balap Karung Helm',
            '🎨 Lomba Mewarnai Tema Kemerdekaan',
            '🏃 Memasukkan Paku Ke Dalam Botol',
            '🥄 Estafet Kelereng Pakai Sendok',
          ],
        },
        {
          id: 's3',
          type: 'content',
          title: 'Kategori Dewasa & Ibu-Ibu',
          subtitle: 'Minggu, 17 Agustus | 13.00 WIB',
          badge: 'KATEGORI DEWASA',
          bgType: 'solid',
          bgColor: '#FFF5F5',
          listItems: [
            '⚽ Futsal Pakai Daster',
            '🎤 Lomba Karaoke Antar RT',
            '🌾 Tarik Tambang Antar Karang Taruna',
            '🎋 Panjat Pinang Akbar Dewasa',
          ],
        },
        {
          id: 's4',
          type: 'statistic',
          title: 'Total Hadiah & Doorprize',
          subtitle: 'Apresiasi Untuk Warga Ter-Hebat',
          badge: 'PRIZE POOL',
          bgType: 'gradient',
          bgGradient: 'linear-gradient(135deg, #F77F00 0%, #FCBF49 100%)',
          statNumber: 'Rp 5.000.000+',
          statLabel: 'Total Hadiah Tunai & Tropy Utama',
        },
        {
          id: 's5',
          type: 'cta',
          title: 'Pendaftaran Gratis!',
          subtitle: 'Hubungi Ketua RT / Panitia Karang Taruna',
          badge: 'DAFTAR SEKARANG',
          bgType: 'solid',
          bgColor: '#1D1D1D',
          ctaPhone: '+62 899-8877-6655 (Panitia 17-an)',
          ctaIg: '@kt.unit08',
          ctaLocation: 'Lapangan Utama Suka Murni',
        },
      ],
    },
  },
  {
    id: 'tpl-organisasi-pengurus',
    name: 'Perkenalan Pengurus / Struktur',
    category: 'organisasi',
    description: 'Post profil pengurus baru Karang Taruna masa bakti.',
    badge: 'Organisasi',
    slideCount: 3,
    projectData: {
      title: 'Struktur Pengurus Karang Taruna Masa Bakti 2026-2029',
      category: 'organisasi',
      aspectRatio: '1:1',
      themeId: 'kt-gold',
      logoType: 'default',
      orgName: 'Karang Taruna Karsa Remaja',
      author: 'Humas Karang Taruna',
      captionText: `🤝 BERSAMA MEMBANGUN PEMUDA 🤝\n\nSelamat dan sukses atas dilantiknya Pengurus Karang Taruna Karsa Remaja Masa Bakti 2026-2029.\n\nMari kita tingkatkan kreativitas, kepedulian sosial, dan jiwa kepemimpinan generasi muda!`,
      hashtags: ['StrukturPengurus', 'KarangTaruna', 'PemudaPancasila', 'Kepemimpinan', 'OrganisasiPemuda'],
      slides: [
        {
          id: 's1',
          type: 'intro',
          title: 'STRUKTUR PENGURUS BARU',
          subtitle: 'Karang Taruna Karsa Remaja 2026-2029',
          badge: 'MASA BAKTI 2026-2029',
          bgType: 'gradient',
          bgGradient: 'linear-gradient(135deg, #1D3557 0%, #457B9D 100%)',
          body: 'Sinergi, Inovatif, & Berintegritas Untuk Kemajuan Desa',
        },
        {
          id: 's2',
          type: 'content',
          title: 'Jajaran Inti Pengurus',
          subtitle: 'Pemimpin Operasional Organisasi',
          badge: 'PENGURUS INTI',
          bgType: 'solid',
          bgColor: '#FFFFFF',
          listItems: [
            '👤 Ketua Umum: Ahmad Fauzi, S.Kom',
            '👤 Wakil Ketua: Rina Permata, S.Pd',
            '📝 Sekretaris: Dimas Anggara',
            '💰 Bendahara: Maya Kartika',
          ],
        },
        {
          id: 's3',
          type: 'outro',
          title: 'Terima Kasih Atas Dukungannya',
          subtitle: 'Bersama Pemuda, Kita Bisa!',
          badge: 'SALAM PEMUDA',
          bgType: 'solid',
          bgColor: '#1D3557',
        },
      ],
    },
  },
  {
    id: 'tpl-umkm-bazaar',
    name: 'Promosi UMKM & Bazaar Pemuda',
    category: 'umkm',
    description: 'Post promosi produk usaha pemuda dan bazaar kuliner Karang Taruna.',
    badge: 'UMKM',
    slideCount: 3,
    projectData: {
      title: 'Bazaar Kuliner & Produk Kreatif Pemuda',
      category: 'umkm',
      aspectRatio: '1:1',
      themeId: 'kt-gold',
      logoType: 'default',
      orgName: 'Karang Taruna Eka Bina',
      author: 'Seksi Ekonomi Kreatif',
      captionText: `🛍️ DUKUNG UMKM PEMUDA LOKAL 🛍️\n\nHadirilah Bazaar Kuliner & Kerajinan Tangan persembahan Karang Taruna! Nikmati aneka aneka cemilan kekinian, jajanan pasar, produk fashion, dan live music.\n\nBelanja lokal, majukan ekonomi tetangga kita! ❤️`,
      hashtags: ['BazaarUMKM', 'EkonomiKreatif', 'ProdukPemuda', 'KulinerLokal', 'KarangTarunaUMKM'],
      slides: [
        {
          id: 's1',
          type: 'intro',
          title: 'BAZAAR KULINER & KREATIF',
          subtitle: 'Dukung Usaha Pemuda & Warga Lokal',
          badge: 'EKONOMI KREATIF',
          bgType: 'gradient',
          bgGradient: 'linear-gradient(135deg, #F77F00 0%, #FCBF49 100%)',
          body: 'Puluhan Stand Kuliner Kekinian & Produk Kreatif',
        },
        {
          id: 's2',
          type: 'content',
          title: 'Fasilitas & Acara Menarik',
          subtitle: 'Seru Untuk Seluruh Keluarga',
          badge: 'HIGHLIGHT',
          bgType: 'solid',
          bgColor: '#FFFFFF',
          listItems: [
            '🍢 30+ Stand Jajanan & Kuliner Nusantara',
            '🎸 Live Acoustic Music Performance',
            '🎁 Doorprize Pembelian Terbanyak',
            '☕ Coffee Corner & Workshop Barista',
          ],
        },
        {
          id: 's3',
          type: 'cta',
          title: 'Mari Merapat & Belanja!',
          subtitle: 'Sabtu - Minggu | 09.00 - 21.00 WIB',
          badge: 'LOKASI BAZAAR',
          bgType: 'solid',
          bgColor: '#1D1D1D',
          ctaPhone: '+62 821-9988-7766 (Seksi Stand)',
          ctaIg: '@kt.ekabina',
          ctaLocation: 'Alun-Alun Kecamatan',
        },
      ],
    },
  },
  {
    id: 'tpl-donasi-kemanusiaan',
    name: 'Open Donasi & Bantuan Kemanusiaan',
    category: 'donasi',
    description: 'Post penggalangan dana korban bencana / kepedulian sosial.',
    badge: 'Donasi',
    slideCount: 3,
    projectData: {
      title: 'Open Donasi Peduli Bencana Alam',
      category: 'donasi',
      aspectRatio: '1:1',
      themeId: 'kt-default',
      logoType: 'default',
      orgName: 'Karang Taruna Peduli',
      author: 'Tim Bantuan Sosial',
      captionText: `🙏 ULURAN TANGAN KITA, HARAPAN MEREKA 🙏\n\nKarang Taruna membuka donasi bantuan kemanusiaan. Salurkan bantuan terbaik Anda berupa uang tunai, pakaian layak pakai, selimut, atau sembako.\n\nSetiap rupiah yang disalurkan sangat berarti untuk saudara kita! ❤️`,
      hashtags: ['OpenDonasi', 'PeduliBencana', 'AksiKemanusiaan', 'KarangTarunaPeduli', 'BantuanSosial'],
      slides: [
        {
          id: 's1',
          type: 'intro',
          title: 'OPEN DONASI PEDULI',
          subtitle: 'Bantuan Kemanusiaan Korban Bencana',
          badge: 'AKSI SOSIAL',
          bgType: 'gradient',
          bgGradient: 'linear-gradient(135deg, #D62828 0%, #1D1D1D 100%)',
          body: 'Mari Bersama Ringankan Beban Saudara Kita',
        },
        {
          id: 's2',
          type: 'content',
          title: 'Bentuk Bantuan Dibutuhkan',
          subtitle: 'Kebutuhan Mendesak Korban',
          badge: 'KEBUTUHAN',
          bgType: 'solid',
          bgColor: '#FFFFFF',
          listItems: [
            '💵 Uang tunai & donasi transfer',
            '📦 Sembako & makanan siap saji',
            '👕 Pakaian layak pakai & selimut',
            '💊 Obat-obatan & perlengkapan bayi',
          ],
        },
        {
          id: 's3',
          type: 'cta',
          title: 'Rekening Resmi Donasi',
          subtitle: 'Bank BCA: 123-456-7890 a.n Karang Taruna Peduli',
          badge: 'POSKO BANTUAN',
          bgType: 'solid',
          bgColor: '#F8FAFC',
          ctaPhone: '+62 813-7788-9900 (Konfirmasi Donasi)',
          ctaIg: '@kt.peduliamal',
          ctaLocation: 'Posko Utama Balai Karang Taruna',
        },
      ],
    },
  },
  {
    id: 'tpl-blank',
    name: 'Project Kosong (Custom Canvas)',
    category: 'blank',
    description: 'Mulai dari halaman kosong dan susun slide sesuai kreativitas Anda.',
    badge: 'Blank',
    slideCount: 1,
    projectData: {
      title: 'Postingan Baru',
      category: 'blank',
      aspectRatio: '1:1',
      themeId: 'kt-default',
      logoType: 'default',
      orgName: 'Karang Taruna',
      author: 'Pengurus Karang Taruna',
      captionText: 'Tuliskan caption postingan di sini...',
      hashtags: ['KarangTaruna', 'PemudaBerkarya'],
      slides: [
        {
          id: 's1',
          type: 'intro',
          title: 'JUDUL UTAMA POSTINGAN',
          subtitle: 'Sub-judul atau Penjelasan Singkat',
          badge: 'KATEGORI POST',
          bgType: 'gradient',
          bgGradient: 'linear-gradient(135deg, #D62828 0%, #F77F00 100%)',
          body: 'Tambahkan deskripsi atau poin penting di sini.',
        },
      ],
    },
  },
];
