import { Theme } from '../types';

export const STARTER_THEMES: Theme[] = [
  {
    id: 'kt-default',
    name: 'Karang Taruna Merah (Klasik)',
    primary: '#D62828',
    secondary: '#F77F00',
    accent: '#FCBF49',
    bg: '#FFFFFF',
    cardBg: '#F8FAFC',
    text: '#1D1D1D',
    textMuted: '#64748B',
    headingFont: 'Poppins, sans-serif',
    bodyFont: 'Inter, sans-serif',
  },
  {
    id: 'kt-dark',
    name: 'Malam Karang Taruna (Dark Luxury)',
    primary: '#E63946',
    secondary: '#F4A261',
    accent: '#E76F51',
    bg: '#121826',
    cardBg: '#1E293B',
    text: '#F8FAFC',
    textMuted: '#94A3B8',
    headingFont: 'Poppins, sans-serif',
    bodyFont: 'Inter, sans-serif',
  },
  {
    id: 'kt-gold',
    name: 'Emas Kemerdekaan (Gold & Navy)',
    primary: '#1D3557',
    secondary: '#E63946',
    accent: '#FCBF49',
    bg: '#F8FAF2',
    cardBg: '#FFFFFF',
    text: '#1D3557',
    textMuted: '#457B9D',
    headingFont: 'Poppins, sans-serif',
    bodyFont: 'Inter, sans-serif',
  },
  {
    id: 'kt-emerald',
    name: 'Hijau Peduli Lingkungan',
    primary: '#2A9D8F',
    secondary: '#E9C46A',
    accent: '#264653',
    bg: '#F4F9F8',
    cardBg: '#FFFFFF',
    text: '#264653',
    textMuted: '#2A9D8F',
    headingFont: 'Poppins, sans-serif',
    bodyFont: 'Inter, sans-serif',
  },
  {
    id: 'kt-minimal',
    name: 'Hitam Putih Clean Minimalis',
    primary: '#18181B',
    secondary: '#3F3F46',
    accent: '#D62828',
    bg: '#FAFAFA',
    cardBg: '#FFFFFF',
    text: '#09090B',
    textMuted: '#71717A',
    headingFont: 'Poppins, sans-serif',
    bodyFont: 'Inter, sans-serif',
  },
];
